"""Public API for :mod:`midi_to_mscz`."""

from .midi_io import MidiReadError, parse_midi, read_midi_file, read_midi_files
from .metadata import infer_score_metadata, key_name
from .pipeline import convert
from .audio_verify import (
    AudioVerificationDependencyError,
    AudioVerificationError,
    get_backend_status,
    verify_audio,
)
from .models import (
    AudioAlignment,
    AudioNoteEvidence,
    AudioReviewItem,
    AudioVerificationResult,
    AudioVerificationSettings,
    AttackGroup,
    ChordEvent,
    ConversionReport,
    ConversionSettings,
    FileReport,
    InputSpec,
    KeyChange,
    KeySignatureEvent,
    MeterChange,
    MidiFileData,
    NoteEvent,
    RestEvent,
    ScoreMetadata,
    TempoChange,
    TempoEvent,
    TimeSignatureEvent,
    TupletGroup,
    VoiceLine,
)

__version__ = "0.4.1"

__all__ = [
    "AudioAlignment",
    "AudioNoteEvidence",
    "AudioReviewItem",
    "AudioVerificationDependencyError",
    "AudioVerificationError",
    "AudioVerificationResult",
    "AudioVerificationSettings",
    "AttackGroup",
    "ChordEvent",
    "ConversionReport",
    "ConversionSettings",
    "FileReport",
    "InputSpec",
    "KeyChange",
    "KeySignatureEvent",
    "MeterChange",
    "MidiFileData",
    "MidiReadError",
    "NoteEvent",
    "RestEvent",
    "ScoreMetadata",
    "TempoChange",
    "TempoEvent",
    "TimeSignatureEvent",
    "TupletGroup",
    "VoiceLine",
    "parse_midi",
    "convert",
    "get_backend_status",
    "infer_score_metadata",
    "key_name",
    "read_midi_file",
    "read_midi_files",
    "verify_audio",
]
