"""MusicXML 4.0 writer for normalized two-staff piano scores."""

from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from bisect import bisect_right
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable, Sequence


DIVISIONS = 96


@dataclass(slots=True)
class _Segment:
    start: Fraction
    end: Fraction
    pitches: tuple[int, ...]
    velocity: int
    staff: str
    voice: int
    arpeggio: str | None = None
    triplet_id: int | str | None = None
    tuplet_actual: int = 3
    tuplet_normal: int = 2
    tuplet_bracket: bool = True
    tuplet_show_number: bool = True
    triplet_start: bool = False
    triplet_stop: bool = False
    grace: bool = False
    grace_slash: bool = True
    grace_order: int = 0
    ornament: str | None = None
    tie_stop: bool = False
    tie_start: bool = False


@dataclass(frozen=True, slots=True)
class _MeasureSpec:
    """One real measure on a possibly changing meter timeline."""

    start: Fraction
    end: Fraction
    numerator: int
    denominator: int
    implicit: bool = False

    @property
    def capacity(self) -> Fraction:
        return self.end - self.start

    @property
    def nominal_capacity(self) -> Fraction:
        return Fraction(self.numerator * 4, self.denominator)


_SHARP_NAMES = (
    ("C", 0),
    ("C", 1),
    ("D", 0),
    ("D", 1),
    ("E", 0),
    ("F", 0),
    ("F", 1),
    ("G", 0),
    ("G", 1),
    ("A", 0),
    ("A", 1),
    ("B", 0),
)
_FLAT_NAMES = (
    ("C", 0),
    ("D", -1),
    ("D", 0),
    ("E", -1),
    ("E", 0),
    ("F", 0),
    ("G", -1),
    ("G", 0),
    ("A", -1),
    ("A", 0),
    ("B", -1),
    ("B", 0),
)


def _get(value: Any, *names: str, default: Any = None) -> Any:
    for name in names:
        if isinstance(value, dict) and name in value:
            return value[name]
        if hasattr(value, name):
            return getattr(value, name)
    return default


def _fraction(value: Any) -> Fraction:
    if isinstance(value, Fraction):
        return value
    if isinstance(value, int):
        return Fraction(value)
    if isinstance(value, float):
        return Fraction(value).limit_denominator(192)
    return Fraction(str(value)).limit_denominator(192)


def _score_events(score: Any) -> list[Any]:
    for name in ("chords", "events", "attacks", "notes"):
        events = _get(score, name)
        if events is not None:
            return list(events)
    voices = _get(score, "voices")
    if voices is not None:
        if isinstance(voices, dict):
            lines: list[Any] = []
            for value in voices.values():
                if isinstance(value, (list, tuple)):
                    lines.extend(value)
                else:
                    lines.append(value)
        else:
            lines = list(voices)
        flattened: list[Any] = []
        for line in lines:
            for event in _get(line, "events", default=()):
                # RestEvent instances are deliberately regenerated by this
                # writer; they need no pitch and may otherwise be duplicated.
                if _get(event, "notes", "pitches", default=None) is not None:
                    flattened.append(event)
        return flattened
    raise ValueError("量化结果没有 chords/events/attacks/notes 字段。")


def _event_to_segment(event: Any) -> _Segment:
    start = _fraction(_get(event, "start", "onset", "start_beat", "quantized_start"))
    end_raw = _get(event, "end", "end_beat", "quantized_end")
    if end_raw is None:
        duration = _fraction(_get(event, "duration", "duration_beats", default=Fraction(1, 4)))
        end = start + duration
    else:
        end = _fraction(end_raw)

    raw_pitches = _get(event, "pitches", "notes")
    if raw_pitches is None:
        raw_pitches = (_get(event, "pitch"),)
    pitches: list[int] = []
    velocity = int(_get(event, "velocity", default=80))
    for item in raw_pitches:
        if isinstance(item, int):
            pitches.append(item)
        else:
            pitch = _get(item, "pitch", "midi_pitch", "transposed_pitch")
            if pitch is not None:
                pitches.append(int(pitch))
            velocity = max(velocity, int(_get(item, "velocity", default=velocity)))
    pitches = sorted(set(pitches))
    if not pitches:
        raise ValueError(f"量化事件缺少音高：{event!r}")

    staff_raw = _get(event, "staff", default="treble")
    staff = str(getattr(staff_raw, "value", staff_raw)).lower()
    if staff in {"upper", "high", "right", "1", "高音", "高音谱表"}:
        staff = "treble"
    elif staff in {"lower", "low", "left", "2", "低音", "低音谱表"}:
        staff = "bass"
    voice = int(_get(event, "voice", "voice_index", default=1))
    if staff == "bass" and voice < 5:
        voice += 4
    if staff == "treble" and voice > 4:
        voice -= 4

    direction = _get(event, "arpeggio", "arpeggio_direction")
    if isinstance(direction, bool):
        direction = "up" if direction else None
    if direction not in ("up", "down"):
        direction = None

    triplet_id = _get(event, "triplet_id", "tuplet_id")
    triplet_start = bool(_get(event, "triplet_start", "tuplet_start", default=False))
    triplet_stop = bool(_get(event, "triplet_stop", "tuplet_stop", default=False))
    grace = bool(_get(event, "grace", "is_grace", default=False))
    return _Segment(
        start=start,
        end=start if grace else max(end, start + Fraction(1, 32)),
        pitches=tuple(pitches),
        velocity=max(1, min(127, velocity)),
        staff=staff,
        voice=voice,
        arpeggio=direction,
        triplet_id=triplet_id,
        triplet_start=triplet_start,
        triplet_stop=triplet_stop,
        grace=grace,
        grace_slash=bool(_get(event, "grace_slash", "slash", default=True)),
        grace_order=int(_get(event, "grace_order", default=0)),
        ornament=_get(event, "ornament", "ornament_kind"),
        tie_stop=bool(_get(event, "tie_stop", "tie_stops", default=False)),
        tie_start=bool(_get(event, "tie_start", "tie_starts", default=False)),
    )


def _pitch_xml(note: ET.Element, midi_pitch: int, fifths: int) -> None:
    midi_pitch = max(0, min(127, midi_pitch))
    step, alter = (_FLAT_NAMES if fifths < 0 else _SHARP_NAMES)[midi_pitch % 12]
    pitch = ET.SubElement(note, "pitch")
    ET.SubElement(pitch, "step").text = step
    if alter:
        ET.SubElement(pitch, "alter").text = str(alter)
    ET.SubElement(pitch, "octave").text = str(midi_pitch // 12 - 1)


def _duration_type(
    duration: Fraction,
    actual_notes: int = 1,
    normal_notes: int = 1,
) -> tuple[str, int]:
    """Return MusicXML type and dot count for an actual duration in beats."""

    written = duration * Fraction(actual_notes, normal_notes)
    candidates: tuple[tuple[Fraction, str, int], ...] = (
        (Fraction(8), "breve", 0),
        (Fraction(6), "whole", 1),
        (Fraction(4), "whole", 0),
        (Fraction(3), "half", 1),
        (Fraction(2), "half", 0),
        (Fraction(3, 2), "quarter", 1),
        (Fraction(1), "quarter", 0),
        (Fraction(3, 4), "eighth", 1),
        (Fraction(1, 2), "eighth", 0),
        (Fraction(3, 8), "16th", 1),
        (Fraction(1, 4), "16th", 0),
        (Fraction(3, 16), "32nd", 1),
        (Fraction(1, 8), "32nd", 0),
        (Fraction(1, 16), "64th", 0),
        (Fraction(1, 32), "128th", 0),
    )
    exact = next(((name, dots) for value, name, dots in candidates if value == written), None)
    if exact:
        return exact
    closest = min(candidates, key=lambda item: abs(float(item[0] - written)))
    return closest[1], closest[2]


def _ticks(duration: Fraction, divisions: int = DIVISIONS) -> int:
    result = duration * divisions
    if result.denominator != 1:
        return max(1, round(float(result)))
    return max(1, result.numerator)


def _choose_divisions(
    segments: Sequence[_Segment],
    measures: Sequence[_MeasureSpec],
    extra_positions: Sequence[Fraction] = (),
) -> int:
    """Choose exact MusicXML divisions, retaining 96 for ordinary notation."""

    divisions = DIVISIONS
    values = [value for measure in measures for value in (measure.start, measure.end)]
    values.extend(extra_positions)
    for segment in segments:
        values.extend((segment.start, segment.end, segment.end - segment.start))
    for value in values:
        if value:
            divisions = math.lcm(divisions, value.denominator)
    return divisions


def _initial_signature(settings: Any, score: Any) -> tuple[int, int]:
    signature = _get(settings, "time_signature", "meter")
    if not signature:
        signature = _get(score, "time_signature", "meter", default=(4, 4))
    if isinstance(signature, str):
        numerator, denominator = (int(part) for part in signature.split("/", 1))
    elif signature:
        numerator, denominator = int(signature[0]), int(signature[1])
    else:
        numerator = int(_get(settings, "numerator", default=4))
        denominator = int(_get(settings, "denominator", default=4))
    return numerator, denominator


def _score_metadata(score: Any) -> Any:
    return _get(score, "metadata", "score_metadata", default=None)


def _meter_changes(settings: Any, score: Any) -> list[tuple[Fraction, int, int]]:
    metadata = _score_metadata(score)
    raw = _get(metadata, "meter_changes", default=None)
    if raw is None:
        raw = _get(score, "meter_changes", "time_signature_changes", default=())
    selected: dict[Fraction, tuple[int, int]] = {}
    for change in raw or ():
        if isinstance(change, (tuple, list)) and len(change) >= 2:
            beat = change[0]
            if isinstance(change[1], (tuple, list)):
                signature = change[1]
            elif len(change) >= 3:
                signature = (change[1], change[2])
            else:
                signature = None
        else:
            beat = _get(change, "beat", "onset", default=0)
            signature = _get(change, "signature", "time_signature", default=None)
        beat = max(Fraction(0), _fraction(beat))
        if signature is not None:
            numerator, denominator = int(signature[0]), int(signature[1])
        else:
            numerator = int(_get(change, "numerator", "beats", default=4))
            denominator = int(_get(change, "denominator", "beat_type", default=4))
        if numerator > 0 and denominator > 0:
            selected[beat] = (numerator, denominator)
    initial = _initial_signature(settings, score)
    if not selected:
        selected[Fraction(0)] = initial
    elif Fraction(0) not in selected:
        selected[Fraction(0)] = initial
    return [
        (beat, signature[0], signature[1])
        for beat, signature in sorted(selected.items())
    ]


def _pickup_length(settings: Any, score: Any, initial_capacity: Fraction) -> Fraction:
    pickup_value = _get(settings, "pickup_beats", default=None)
    if not pickup_value:
        pickup_value = _get(score, "pickup_beats", "pickup", default=0)
    if not pickup_value:
        pickup_value = _get(_score_metadata(score), "pickup_beats", default=0)
    pickup = _fraction(pickup_value)
    if pickup < 0 or pickup >= initial_capacity:
        pickup = Fraction(0)
    return pickup


def _tempo_changes(settings: Any, score: Any) -> list[tuple[Fraction, float]]:
    metadata = _score_metadata(score)
    raw = _get(metadata, "tempo_changes", default=None)
    if raw is None:
        raw = _get(score, "tempo_changes", "tempo_map", default=())
    selected: dict[Fraction, float] = {}
    for change in raw or ():
        if isinstance(change, (tuple, list)) and len(change) >= 2:
            beat, bpm = change[0], change[1]
        else:
            beat = _get(change, "beat", "onset", default=0)
            bpm = _get(change, "bpm", "tempo", default=None)
        if bpm is not None and float(bpm) > 0:
            selected[max(Fraction(0), _fraction(beat))] = float(bpm)
    fallback = (
        _get(score, "bpm", "tempo", default=None)
        or _get(settings, "bpm", default=None)
        or 120
    )
    if not selected:
        selected[Fraction(0)] = float(fallback)
    elif Fraction(0) not in selected:
        first_beat = min(selected)
        selected[Fraction(0)] = selected[first_beat]
    return sorted(selected.items())


def _key_changes(settings: Any, score: Any) -> list[tuple[Fraction, int, str]]:
    metadata = _score_metadata(score)
    raw = _get(metadata, "key_changes", default=None)
    if raw is None:
        raw = _get(score, "key_changes", "key_signature_changes", default=())
    selected: dict[Fraction, tuple[int, str]] = {}
    for change in raw or ():
        if isinstance(change, (tuple, list)) and len(change) >= 2:
            beat, fifths = change[0], change[1]
            mode = change[2] if len(change) >= 3 else "major"
        else:
            beat = _get(change, "beat", "onset", default=0)
            fifths = _get(change, "fifths", "key_fifths", default=None)
            mode = _get(change, "mode", default="major")
        if fifths is not None:
            selected[max(Fraction(0), _fraction(beat))] = (
                max(-7, min(7, int(fifths))),
                "minor" if str(mode).lower() == "minor" else "major",
            )
    fallback_fifths = _get(
        settings, "key_fifths", "key_signature", "fifths", default=None
    )
    if fallback_fifths is None:
        fallback_fifths = _get(
            score, "key_fifths", "key_signature", "fifths", default=0
        )
    fallback_mode = str(_get(score, "key_mode", default="major"))
    if not selected:
        selected[Fraction(0)] = (
            int(fallback_fifths or 0),
            "minor" if fallback_mode == "minor" else "major",
        )
    elif Fraction(0) not in selected:
        selected[Fraction(0)] = selected[min(selected)]
    return [
        (beat, value[0], value[1]) for beat, value in sorted(selected.items())
    ]


def _effective_change(changes: Sequence[tuple[Any, ...]], beat: Fraction) -> tuple[Any, ...]:
    effective = changes[0]
    for change in changes:
        if change[0] > beat:
            break
        effective = change
    return effective


def _build_measure_specs(
    settings: Any,
    score: Any,
    score_end: Fraction,
) -> list[_MeasureSpec]:
    """Create measure bounds while honouring temporary time-signature changes."""

    changes = _meter_changes(settings, score)
    initial_numerator, initial_denominator = changes[0][1], changes[0][2]
    initial_capacity = Fraction(initial_numerator * 4, initial_denominator)
    pickup = _pickup_length(settings, score, initial_capacity)
    cursor = Fraction(0)
    measures: list[_MeasureSpec] = []
    change_index = 0
    numerator, denominator = initial_numerator, initial_denominator

    if pickup:
        measures.append(
            _MeasureSpec(cursor, pickup, numerator, denominator, implicit=True)
        )
        cursor = pickup

    target_end = max(score_end, cursor + Fraction(1, 32))
    while cursor < target_end or not measures:
        while change_index < len(changes) and changes[change_index][0] <= cursor:
            _beat, numerator, denominator = changes[change_index]
            change_index += 1
        nominal = Fraction(numerator * 4, denominator)
        end = cursor + nominal
        if change_index < len(changes):
            next_change = changes[change_index][0]
            if cursor < next_change < end:
                end = next_change
        if end <= cursor:
            raise ValueError("拍号变化产生了零长度小节。")
        measures.append(
            _MeasureSpec(
                cursor,
                end,
                numerator,
                denominator,
                implicit=(end - cursor != nominal),
            )
        )
        cursor = end
    return measures


def _measure_index(beat: Fraction, measures: Sequence[_MeasureSpec]) -> int:
    starts = [measure.start for measure in measures]
    index = bisect_right(starts, beat) - 1
    return max(0, min(index, len(measures) - 1))


def _split_segments(
    source_segments: Iterable[_Segment], measures: Sequence[_MeasureSpec]
) -> list[_Segment]:
    pieces: list[_Segment] = []
    for segment in source_segments:
        if segment.grace:
            cursor = max(Fraction(0), segment.start)
            segment.start = cursor
            segment.end = cursor
            pieces.append(segment)
            continue
        cursor = max(Fraction(0), segment.start)
        end = max(cursor + Fraction(1, 32), segment.end)
        piece_index = 0
        notation_values = (
            Fraction(8), Fraction(6), Fraction(4), Fraction(3), Fraction(2),
            Fraction(3, 2), Fraction(1), Fraction(3, 4), Fraction(1, 2),
            Fraction(3, 8), Fraction(1, 4), Fraction(3, 16), Fraction(1, 8),
            Fraction(1, 16), Fraction(1, 32),
        )
        while cursor < end:
            measure_index = _measure_index(cursor, measures)
            measure_end = measures[measure_index].end
            available = min(end, measure_end) - cursor
            if segment.triplet_id is not None:
                written_available = available * Fraction(
                    segment.tuplet_actual, segment.tuplet_normal
                )
                # Tuplet members often use base types smaller than a 64th
                # (e.g. one-beat 5:4); MusicXML can carry the exact duration
                # and ratio even when our display-type candidate table has no
                # exact entry.  Do not decompose a single tuplet slot merely
                # because it lies below that table's minimum.
                # The quantizer already emits each tuplet member at a valid
                # slot boundary.  Its written type is inferred separately;
                # retaining this complete duration avoids fragmenting one
                # 5th/7th/9th slot into several tied pseudo-members.
                written_piece = written_available
                piece_duration = written_piece * Fraction(
                    segment.tuplet_normal, segment.tuplet_actual
                )
            else:
                piece_duration = next(
                    (value for value in notation_values if value <= available),
                    available,
                )
            piece_end = cursor + piece_duration
            if piece_end <= cursor:
                break
            pieces.append(
                _Segment(
                    start=cursor,
                    end=piece_end,
                    pitches=segment.pitches,
                    velocity=segment.velocity,
                    staff=segment.staff,
                    voice=segment.voice,
                    arpeggio=segment.arpeggio if piece_index == 0 else None,
                    triplet_id=segment.triplet_id,
                    tuplet_actual=segment.tuplet_actual,
                    tuplet_normal=segment.tuplet_normal,
                    tuplet_bracket=segment.tuplet_bracket,
                    tuplet_show_number=segment.tuplet_show_number,
                    triplet_start=segment.triplet_start and piece_index == 0,
                    triplet_stop=segment.triplet_stop and piece_end == end,
                    ornament=segment.ornament if piece_index == 0 else None,
                    tie_stop=(segment.tie_stop if piece_index == 0 else True),
                    tie_start=(
                        piece_end < end
                        or (segment.tie_start and piece_end == end)
                    ),
                )
            )
            cursor = piece_end
            piece_index += 1
    return pieces


def _add_notations(
    note: ET.Element,
    *,
    arpeggio: str | None,
    tie_stop: bool,
    tie_start: bool,
    triplet_start: bool,
    triplet_stop: bool,
    tuplet_bracket: bool = True,
    tuplet_show_number: bool = True,
    ornament: str | None = None,
) -> None:
    if not any((arpeggio, tie_stop, tie_start, triplet_start, triplet_stop, ornament)):
        return
    notations = ET.SubElement(note, "notations")
    if tie_stop:
        ET.SubElement(notations, "tied", {"type": "stop"})
    if tie_start:
        ET.SubElement(notations, "tied", {"type": "start"})
    if triplet_start:
        ET.SubElement(
            notations,
            "tuplet",
            {
                "type": "start",
                "number": "1",
                "bracket": "yes" if tuplet_bracket else "no",
                "show-number": "actual" if tuplet_show_number else "none",
            },
        )
    if triplet_stop:
        ET.SubElement(notations, "tuplet", {"type": "stop", "number": "1"})
    ornament_tags = {
        "trill": "trill-mark",
        "trill-mark": "trill-mark",
        "mordent": "mordent",
        "inverted-mordent": "inverted-mordent",
        "turn": "turn",
        "inverted-turn": "inverted-turn",
        "delayed-turn": "delayed-turn",
        "delayed-inverted-turn": "delayed-inverted-turn",
        "vertical-turn": "vertical-turn",
        "shake": "shake",
        "schleifer": "schleifer",
        "haydn": "haydn",
    }
    ornament_tag = ornament_tags.get(str(ornament or "").lower())
    if ornament_tag:
        ornaments = ET.SubElement(notations, "ornaments")
        ET.SubElement(ornaments, ornament_tag)
    elif str(ornament or "").lower() == "tremolo":
        ornaments = ET.SubElement(notations, "ornaments")
        ET.SubElement(ornaments, "tremolo", {"type": "single"}).text = "3"
    if arpeggio:
        ET.SubElement(notations, "arpeggiate", {"number": "1", "direction": arpeggio})


def _write_rest(
    parent: ET.Element,
    duration: Fraction,
    voice: int,
    staff: int,
    divisions: int,
) -> None:
    if duration <= 0:
        return
    # Break unusual gaps into notatable values.  This avoids one rest whose
    # type disagrees with its duration, which importers tend to rewrite badly.
    remaining = duration
    values = (
        Fraction(8), Fraction(6), Fraction(4), Fraction(3), Fraction(2),
        Fraction(3, 2), Fraction(1), Fraction(3, 4), Fraction(1, 2),
        Fraction(3, 8), Fraction(1, 4), Fraction(3, 16), Fraction(1, 8),
        Fraction(1, 16), Fraction(1, 32),
    )
    while remaining > 0:
        value = next((candidate for candidate in values if candidate <= remaining), remaining)
        note = ET.SubElement(parent, "note")
        ET.SubElement(note, "rest")
        ET.SubElement(note, "duration").text = str(_ticks(value, divisions))
        ET.SubElement(note, "voice").text = str(voice)
        note_type, dots = _duration_type(value)
        ET.SubElement(note, "type").text = note_type
        for _ in range(dots):
            ET.SubElement(note, "dot")
        ET.SubElement(note, "staff").text = str(staff)
        remaining -= value


def _write_chord(
    parent: ET.Element,
    segment: _Segment,
    relative_start: Fraction,
    fifths: int,
    divisions: int,
) -> None:
    duration = segment.end - segment.start
    is_tuplet = segment.triplet_id is not None
    note_type, dots = _duration_type(
        duration,
        segment.tuplet_actual if is_tuplet else 1,
        segment.tuplet_normal if is_tuplet else 1,
    ) if not segment.grace else ("eighth", 0)
    for index, midi_pitch in enumerate(segment.pitches):
        note = ET.SubElement(parent, "note")
        if segment.grace:
            ET.SubElement(note, "grace", {"slash": "yes" if segment.grace_slash else "no"})
        if index:
            ET.SubElement(note, "chord")
        _pitch_xml(note, midi_pitch, fifths)
        if not segment.grace:
            ET.SubElement(note, "duration").text = str(_ticks(duration, divisions))
        if segment.tie_stop:
            ET.SubElement(note, "tie", {"type": "stop"})
        if segment.tie_start:
            ET.SubElement(note, "tie", {"type": "start"})
        ET.SubElement(note, "voice").text = str(segment.voice)
        ET.SubElement(note, "type").text = note_type
        for _ in range(dots):
            ET.SubElement(note, "dot")
        if is_tuplet:
            modification = ET.SubElement(note, "time-modification")
            ET.SubElement(modification, "actual-notes").text = str(segment.tuplet_actual)
            ET.SubElement(modification, "normal-notes").text = str(segment.tuplet_normal)
        ET.SubElement(note, "staff").text = "1" if segment.staff == "treble" else "2"
        _add_notations(
            note,
            arpeggio=segment.arpeggio,
            tie_stop=segment.tie_stop,
            tie_start=segment.tie_start,
            triplet_start=segment.triplet_start and index == 0,
            triplet_stop=segment.triplet_stop and index == 0,
            tuplet_bracket=segment.tuplet_bracket,
            tuplet_show_number=segment.tuplet_show_number,
            ornament=segment.ornament if index == 0 else None,
        )


def build_musicxml(score: Any, settings: Any) -> ET.ElementTree:
    """Build a MusicXML tree from the normalized score returned by quantize."""

    events = _score_events(score)
    raw_segments = [_event_to_segment(event) for event in events]
    declared_duration = _fraction(_get(score, "duration", default=0) or 0)
    score_end = max(
        [declared_duration]
        + [segment.end for segment in raw_segments if not segment.grace]
        + [segment.start for segment in raw_segments if segment.grace]
    )
    measures = _build_measure_specs(settings, score, score_end)
    tempo_changes = _tempo_changes(settings, score)
    key_changes = _key_changes(settings, score)
    # Tuplet membership is represented as separate groups by the quantizer.
    # Keep boundary ids here; slotted ChordEvent objects should not be mutated.
    tuplets = list(_get(score, "tuplets", default=()) or ())
    events_by_id = {_get(event, "event_id", "id"): event for event in events}
    tuplet_boundaries: dict[
        Any, tuple[Any, Any, int, int, bool, bool, Fraction, Fraction]
    ] = {}
    for group in tuplets:
        members = list(_get(group, "member_event_ids", default=()) or ())
        if members:
            member_events = [events_by_id[member] for member in members if member in events_by_id]
            derived_start = min(
                (
                    _fraction(_get(event, "onset", "start", "start_beat", "quantized_start"))
                    for event in member_events
                ),
                default=Fraction(0),
            )
            derived_end = max(
                (
                    _fraction(_get(event, "onset", "start", "start_beat", "quantized_start"))
                    + _fraction(_get(event, "duration", "duration_beats", default=Fraction(0)))
                    for event in member_events
                ),
                default=derived_start,
            )
            start_value = _get(group, "start", default=None)
            end_value = _get(group, "end", default=None)
            tuplet_boundaries[_get(group, "tuplet_id")] = (
                members[0],
                members[-1],
                int(_get(group, "actual_notes", default=3)),
                int(_get(group, "normal_notes", default=2)),
                bool(_get(group, "bracket", default=True)),
                bool(_get(group, "show_number", default=True)),
                derived_start if start_value is None else _fraction(start_value),
                derived_end if end_value is None else _fraction(end_value),
            )
    # Tuplet-to-straight continuations are explicit model events.  Keeping the
    # split in quantization makes voice invariants, reports, tests and every
    # output backend see the same no-rest timeline.
    segments = _split_segments(raw_segments, measures)
    event_tuplet_boundaries: dict[tuple[Fraction, int, Any], tuple[bool, bool]] = {}
    for event in events:
        tuplet_id = _get(event, "tuplet_id", "triplet_id")
        boundaries = tuplet_boundaries.get(tuplet_id)
        if boundaries:
            event_id = _get(event, "event_id", "id")
            onset = _fraction(_get(event, "onset", "start", "start_beat", "quantized_start"))
            voice = int(_get(event, "voice", "voice_index", default=1))
            staff = str(_get(event, "staff", default="treble"))
            if "bass" in staff and voice < 5:
                voice += 4
            event_tuplet_boundaries[(onset, voice, tuplet_id)] = (
                event_id == boundaries[0], event_id == boundaries[1]
            )
    for segment in segments:
        boundary = event_tuplet_boundaries.get((segment.start, segment.voice, segment.triplet_id))
        if boundary:
            segment.triplet_start, segment.triplet_stop = boundary
        if segment.triplet_id in tuplet_boundaries:
            info = tuplet_boundaries[segment.triplet_id]
            segment.tuplet_actual = info[2]
            segment.tuplet_normal = info[3]
            segment.tuplet_bracket = info[4]
            segment.tuplet_show_number = info[5]
            # Apply group boundaries to split segments, not merely to the
            # original event onset.  This keeps a tuplet bracket valid when a
            # tied member crosses a barline.
            segment.triplet_start = segment.start == info[6]
            segment.triplet_stop = segment.end == info[7]
    divisions = _choose_divisions(
        segments,
        measures,
        [change[0] for change in tempo_changes]
        + [change[0] for change in key_changes],
    )
    measure_count = len(measures)
    title = str(_get(settings, "title", default="") or _get(score, "title", default="") or "标准化钢琴谱")
    composer = str(_get(settings, "composer", default="") or "")
    swing_regions = list(_get(score, "swing_regions", default=()) or ())
    if not swing_regions:
        swing_ratio = _get(score, "swing_ratio", default=None)
        if swing_ratio:
            swing_regions = [(Fraction(0), measures[-1].end, swing_ratio)]

    root = ET.Element("score-partwise", {"version": "4.0"})
    work = ET.SubElement(root, "work")
    ET.SubElement(work, "work-title").text = title
    identification = ET.SubElement(root, "identification")
    if composer:
        ET.SubElement(identification, "creator", {"type": "composer"}).text = composer
    encoding = ET.SubElement(identification, "encoding")
    ET.SubElement(encoding, "software").text = "MIDI to MSCZ Normalizer"

    part_list = ET.SubElement(root, "part-list")
    score_part = ET.SubElement(part_list, "score-part", {"id": "P1"})
    ET.SubElement(score_part, "part-name").text = "Piano"
    ET.SubElement(score_part, "part-abbreviation").text = "Pno."
    score_instrument = ET.SubElement(score_part, "score-instrument", {"id": "P1-I1"})
    ET.SubElement(score_instrument, "instrument-name").text = "Acoustic Grand Piano"
    ET.SubElement(score_instrument, "instrument-sound").text = "keyboard.piano"
    midi_instrument = ET.SubElement(score_part, "midi-instrument", {"id": "P1-I1"})
    ET.SubElement(midi_instrument, "midi-channel").text = "1"
    ET.SubElement(midi_instrument, "midi-program").text = "1"

    part = ET.SubElement(root, "part", {"id": "P1"})
    previous_signature: tuple[int, int] | None = None
    previous_key: tuple[int, str] | None = None
    for measure_index, measure_spec in enumerate(measures):
        measure_start, measure_end = measure_spec.start, measure_spec.end
        capacity = measure_spec.capacity
        numerator, denominator = measure_spec.numerator, measure_spec.denominator
        _key_beat, fifths, key_mode = _effective_change(key_changes, measure_start)
        signature = (numerator, denominator)
        current_key = (int(fifths), str(key_mode))
        attributes_dict = {"number": str(measure_index + 1)}
        if measure_spec.implicit:
            attributes_dict["implicit"] = "yes"
        measure = ET.SubElement(part, "measure", attributes_dict)
        if (
            measure_index == 0
            or signature != previous_signature
            or current_key != previous_key
        ):
            attributes = ET.SubElement(measure, "attributes")
            if measure_index == 0:
                ET.SubElement(attributes, "divisions").text = str(divisions)
            if measure_index == 0 or current_key != previous_key:
                key = ET.SubElement(attributes, "key")
                ET.SubElement(key, "fifths").text = str(fifths)
                ET.SubElement(key, "mode").text = str(key_mode)
            if measure_index == 0 or signature != previous_signature:
                time = ET.SubElement(attributes, "time")
                ET.SubElement(time, "beats").text = str(numerator)
                ET.SubElement(time, "beat-type").text = str(denominator)
            if measure_index == 0:
                ET.SubElement(attributes, "staves").text = "2"
                clef1 = ET.SubElement(attributes, "clef", {"number": "1"})
                ET.SubElement(clef1, "sign").text = "G"
                ET.SubElement(clef1, "line").text = "2"
                clef2 = ET.SubElement(attributes, "clef", {"number": "2"})
                ET.SubElement(clef2, "sign").text = "F"
                ET.SubElement(clef2, "line").text = "4"
        previous_signature = signature
        previous_key = current_key

        for tempo_beat, tempo_bpm in tempo_changes:
            if not measure_start <= tempo_beat < measure_end:
                continue
            direction = ET.SubElement(measure, "direction", {"placement": "above"})
            direction_type = ET.SubElement(direction, "direction-type")
            metronome = ET.SubElement(direction_type, "metronome")
            ET.SubElement(metronome, "beat-unit").text = "quarter"
            ET.SubElement(metronome, "per-minute").text = f"{tempo_bpm:g}"
            offset = tempo_beat - measure_start
            if offset:
                ET.SubElement(direction, "offset", {"sound": "yes"}).text = str(
                    _ticks(offset, divisions)
                )
            ET.SubElement(direction, "sound", {"tempo": f"{tempo_bpm:g}"})

        for region in swing_regions:
            region_start = _fraction(region[0])
            region_end = _fraction(region[1])
            region_ratio = region[2]
            if measure_start <= region_start < measure_end:
                swing_direction = ET.SubElement(
                    measure, "direction", {"placement": "above"}
                )
                swing_text = ET.SubElement(swing_direction, "direction-type")
                ET.SubElement(swing_text, "words").text = "Swing"
                start_offset = region_start - measure_start
                if start_offset:
                    ET.SubElement(swing_direction, "offset").text = str(
                        _ticks(start_offset, divisions)
                    )
                swing_sound = ET.SubElement(swing_direction, "sound")
                swing = ET.SubElement(swing_sound, "swing")
                ET.SubElement(swing, "first").text = str(int(region_ratio[0]))
                ET.SubElement(swing, "second").text = str(int(region_ratio[1]))
                ET.SubElement(swing, "swing-type").text = "eighth"
            if measure_start <= region_end < measure_end:
                straight_direction = ET.SubElement(
                    measure, "direction", {"placement": "above"}
                )
                straight_text = ET.SubElement(straight_direction, "direction-type")
                ET.SubElement(straight_text, "words").text = "Straight"
                end_offset = region_end - measure_start
                if end_offset:
                    ET.SubElement(straight_direction, "offset").text = str(
                        _ticks(end_offset, divisions)
                    )
                straight_sound = ET.SubElement(straight_direction, "sound")
                ET.SubElement(straight_sound, "swing").append(
                    ET.Element("straight")
                )

        in_measure = [
            segment for segment in segments
            if measure_start <= segment.start < measure_end
        ]
        voice_ids = sorted({segment.voice for segment in in_measure})
        if not voice_ids:
            voice_ids = [1, 5]
        # Always include a voice on both staves, otherwise an entirely empty
        # staff can disappear in compact import layouts.
        if not any(voice <= 4 for voice in voice_ids):
            voice_ids.insert(0, 1)
        if not any(voice >= 5 for voice in voice_ids):
            voice_ids.append(5)

        for voice_position, voice in enumerate(voice_ids):
            if voice_position:
                backup = ET.SubElement(measure, "backup")
                ET.SubElement(backup, "duration").text = str(_ticks(capacity, divisions))
            staff_number = 1 if voice <= 4 else 2
            cursor = measure_start
            voice_segments = sorted(
                (segment for segment in in_measure if segment.voice == voice),
                key=lambda segment: (
                    segment.start,
                    0 if segment.grace else 1,
                    segment.grace_order,
                    segment.pitches,
                ),
            )
            if not voice_segments:
                rest_note = ET.SubElement(
                    measure, "note", {"print-object": "no", "print-spacing": "yes"}
                )
                ET.SubElement(rest_note, "rest", {"measure": "yes"})
                ET.SubElement(rest_note, "duration").text = str(_ticks(capacity, divisions))
                ET.SubElement(rest_note, "voice").text = str(voice)
                ET.SubElement(rest_note, "type").text = "whole"
                ET.SubElement(rest_note, "staff").text = str(staff_number)
                continue
            for segment in voice_segments:
                if segment.start > cursor:
                    _write_rest(
                        measure,
                        segment.start - cursor,
                        voice,
                        staff_number,
                        divisions,
                    )
                    cursor = segment.start
                if segment.grace:
                    _write_chord(
                        measure,
                        segment,
                        segment.start - measure_start,
                        fifths,
                        divisions,
                    )
                    continue
                if segment.start < cursor:
                    raise ValueError(
                        "同一 MusicXML 声部存在重叠事件："
                        f"voice={voice}, onset={segment.start}, previous_end={cursor}。"
                        "量化阶段必须先分配或明确截断声部，不能在导出时移动攻击。"
                    )
                if segment.end > measure_end:
                    segment.end = measure_end
                _write_chord(
                    measure,
                    segment,
                    segment.start - measure_start,
                    fifths,
                    divisions,
                )
                cursor = segment.end
            if cursor < measure_end:
                _write_rest(
                    measure,
                    measure_end - cursor,
                    voice,
                    staff_number,
                    divisions,
                )
    return ET.ElementTree(root)


def write_musicxml(score: Any, settings: Any, path: str | Path) -> Path:
    """Serialize ``score`` as UTF-8 MusicXML and return the output path."""

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    tree = build_musicxml(score, settings)
    try:
        ET.indent(tree, space="  ")
    except AttributeError:  # Python 3.8 compatibility
        pass
    tree.write(output, encoding="utf-8", xml_declaration=True)
    return output


__all__ = ["DIVISIONS", "build_musicxml", "write_musicxml"]
